version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:13

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  stravabox:
    <<: *defaults
    steps:
      - install
      - restore_cache:
          keys:
            - strava-auth-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - strava-auth-
      - run: npm start
      - save_cache:
          key: strava-auth-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - strava-auth.json

workflows:
  version: 2

  test:
    jobs:
      - stravabox

  poll:
    triggers:
      - schedule:
          # Run once nightly at 10pm
          cron: "00 22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - stravabox
